# Generated by Django 2.0.2 on 2018-02-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='iata_code',
            field=models.CharField(blank=True, default=None, max_length=3, null=True, verbose_name='Код аэропорта ИАТА'),
        ),
        migrations.AlterField(
            model_name='city',
            name='rzd_code',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Код ж/д станции'),
        ),
    ]
