# Generated by Django 2.0.2 on 2018-02-24 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0002_auto_20180224_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TRAIN', 'Train'), ('PLANE', 'Airplane')], default='TRAIN', max_length=5)),
                ('from_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_city', to='robot.City')),
                ('to_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_city', to='robot.City')),
            ],
        ),
    ]
