# Generated by Django 2.0.2 on 2018-02-24 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('departure', models.DateTimeField()),
                ('arrive', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('free_seats', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('carrier', models.CharField(max_length=40, verbose_name='Перевозчик')),
                ('carrier_description', models.CharField(max_length=40, verbose_name='Название поезда или тип самолёта')),
                ('trip_number', models.CharField(max_length=6, verbose_name='Номер рейса или номер поезда')),
            ],
        ),
        migrations.AlterField(
            model_name='route',
            name='type',
            field=models.CharField(choices=[('PLANE', 'Airplane'), ('TRAIN', 'Train')], default='TRAIN', max_length=5),
        ),
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Route'),
        ),
    ]
