# Generated by Django 2.0.2 on 2018-02-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0004_auto_20180224_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('car_class', models.CharField(max_length=40, verbose_name='Тип вагона или места в самолёте')),
                ('free_seats', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='carrier_description',
            new_name='car_description',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='free_seats',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='min_price',
        ),
        migrations.AlterField(
            model_name='route',
            name='type',
            field=models.CharField(choices=[('TRAIN', 'Train'), ('PLANE', 'Airplane')], default='TRAIN', max_length=5),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Route'),
        ),
        migrations.AddField(
            model_name='price',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trip'),
        ),
    ]
