# Generated by Django 2.0.2 on 2018-02-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0005_auto_20180225_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='car_description',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя поезда или тип самолёта'),
        ),
    ]
