# Generated by Django 2.0.2 on 2018-02-25 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0007_auto_20180225_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Route'),
        ),
    ]
