# Generated by Django 2.0.2 on 2018-02-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0008_auto_20180225_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='descr',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='way',
            name='type',
            field=models.CharField(choices=[('PLANE', 'Airplane'), ('TRAIN', 'Train')], default='TRAIN', max_length=5),
        ),
    ]
