# Generated by Django 2.0.2 on 2018-03-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0010_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='way',
            name='type',
            field=models.CharField(choices=[('TRAIN', 'Train'), ('PLANE', 'Airplane')], default='TRAIN', max_length=5),
        ),
    ]
