# Generated by Django 2.0.2 on 2018-03-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0011_auto_20180328_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='departure_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='way',
            name='type',
            field=models.CharField(choices=[('PLANE', 'Airplane'), ('TRAIN', 'Train')], default='TRAIN', max_length=5),
        ),
    ]
