# Generated by Django 2.0.2 on 2018-04-03 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0013_auto_20180403_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='way',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='robot.Way'),
        ),
    ]
