# Generated by Django 2.0.2 on 2018-04-03 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0014_train_way'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Train'),
        ),
        migrations.AlterField(
            model_name='train',
            name='way',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Way'),
        ),
    ]
