# Generated by Django 2.0.2 on 2018-04-05 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0015_auto_20180403_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='route',
        ),
        migrations.AddField(
            model_name='route',
            name='price_coupe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='price_platzkart',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='price_seated',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='seats_coupe',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='seats_platzkart',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='seats_seated',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
