# Generated by Django 2.0.2 on 2018-04-11 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0016_jsondump'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonDump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, default='downloaded', max_length=20, null=True)),
                ('date_to', models.DateField(null=True)),
                ('date_from', models.DateField(null=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('trains_to_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('trains_from_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('way', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Way')),
            ],
        ),
        migrations.CreateModel(
            name='RouteArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('departure', models.DateTimeField(null=True)),
                ('departure_time', models.TimeField(null=True)),
                ('arrive', models.DateTimeField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('price_seated', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_platzkart', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_coupe', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('seats_seated', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seats_platzkart', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seats_coupe', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('train', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Train')),
                ('way', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Way')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
