# Generated by Django 2.0.2 on 2018-04-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0018_auto_20180411_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondump',
            name='request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
