# Generated by Django 2.0.2 on 2018-04-15 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0019_auto_20180411_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='way',
            name='from_city',
        ),
        migrations.AddField(
            model_name='way',
            name='city_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_from', to='robot.City'),
        ),
    ]
