# Generated by Django 2.0.2 on 2018-04-15 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0020_auto_20180415_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='way',
            name='to_city',
        ),
        migrations.AddField(
            model_name='way',
            name='city_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_to', to='robot.City'),
        ),
    ]
