# Generated by Django 2.0.2 on 2018-04-15 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0021_auto_20180415_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='way',
            name='direction',
            field=models.CharField(default='to', max_length=4, verbose_name='Направление маршрута туда/обратно: to/from'),
        ),
        migrations.AddField(
            model_name='trip',
            name='way_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='way_from', to='robot.Way'),
        ),
        migrations.AddField(
            model_name='trip',
            name='way_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='way_to', to='robot.Way'),
        ),
        migrations.AddField(
            model_name='way',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Trip'),
        ),
    ]
