# Generated by Django 2.0.2 on 2018-04-15 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0022_auto_20180415_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='way',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Trip'),
        ),
    ]
