# Generated by Django 2.0.2 on 2018-04-15 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0023_auto_20180415_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.City'),
        ),
    ]
