# Generated by Django 2.0.2 on 2018-04-15 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0024_trip_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='city',
        ),
        migrations.AddField(
            model_name='trip',
            name='city_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_city_from', to='robot.City'),
        ),
        migrations.AddField(
            model_name='trip',
            name='city_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_city_to', to='robot.City'),
        ),
        migrations.AlterField(
            model_name='way',
            name='city_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='way_city_from', to='robot.City'),
        ),
        migrations.AlterField(
            model_name='way',
            name='city_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='way_city_to', to='robot.City'),
        ),
    ]
