# Generated by Django 2.0.2 on 2018-04-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0025_auto_20180415_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='way',
        ),
    ]
