# Generated by Django 2.0.2 on 2018-04-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0026_remove_train_way'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Имя файла дампа, содержащее маршрут этого поезда'),
        ),
    ]
