# Generated by Django 2.0.2 on 2018-04-15 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0027_train_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='filename',
        ),
        migrations.AddField(
            model_name='train',
            name='city_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='train_city_from', to='robot.City'),
        ),
        migrations.AddField(
            model_name='train',
            name='city_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='train_city_to', to='robot.City'),
        ),
    ]
