# Generated by Django 2.0.2 on 2018-04-15 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0028_auto_20180415_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsondump',
            name='way',
        ),
        migrations.AddField(
            model_name='jsondump',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Trip'),
        ),
    ]
